apiVersion: apps/event
kind: Deployment
metadata:
  name: event_deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event_container
          image: ../../services/event/ #ссылка на контейнер в docker hub
          imagePullPolicy: Always
          ports:
            - containerPort: 84