apiVersion: apps/messenger
kind: Deployment
metadata:
  name: messenger_deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - name: messenger_container
          image: ../../services/messenger/ #ссылка на контейнер в docker hub
          imagePullPolicy: Always
          ports:
            - containerPort: 82