apiVersion: apps/mongo
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      tool: mongo_service
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        tool: mongo_container
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 180
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        storageClassName: "fast"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi