apiVersion: apps/shorts
kind: Deployment
metadata:
  name: shorts_deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shorts
    spec:
      containers:
        - name: shorts_container
          image: ../../services/shorts/ #ссылка на контейнер в docker hub
          imagePullPolicy: Always
          ports:
            - containerPort: 83